name: 'Test'

on:
  pull_request:
    branches:
      - master
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout repository
        uses: actions/checkout@v3
      - id: unit_test
        name: unit test
        run: |
          ./gradlew testDebugUnitTest
